version: '2'

services:
    mariadb:
        image: mariadb:10.1
        volumes:    
        - db_data:/var/lib/mysql
        - ./lf_db/structure:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: lionfreaky
            MYSQL_USER: lionfreaky
            MYSQL_PASSWORD: ${MYSQL_LIONFREAKY_PASSWORD}
        ports:
        - "3406:3306"
    apache:
        depends_on:
        - mariadb
        - php-composer
        build: ./docker/Apache2/
        image: lionfreaky-apache:latest
        ports:
        - "${APACHE_PORT}:80"
        volumes:
        - .:/var/www/html
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
        - mariadb 
        ports:
        - "${PHPMYADMIN_PORT}:80"              
        environment:
            PMA_HOST: mariadb  
    php-composer:
        image: composer:1.7.2
        volumes:
        - ./laravel-5.7.0:/app
        command: install
        #command: update
volumes:
    db_data:

        
