name: Trigger DBLOAD

on:
  schedule:
    - cron:  '30 3 * * *'
  workflow_dispatch:

jobs:
  dbload:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: wget -S --no-check-certificate https://competitie.badminton-pbo.be/dbload/true/true

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1