name: Trigger DBLOAD

on:
  schedule:
    - cron:  '30 3 * * *'
  workflow_dispatch:

jobs:
  dbload:
    runs-on: ubuntu-20.04
    steps:
      - name: trigger
        run: wget -S --no-check-certificate https://competitie.badminton-pbo.be/dbload/true/true
